### ISSUE TITLE
Import tokens token information from marketcap.cash or similar sites

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-analytics#29]
Edit src/core/tokeninfo.js to add tokens information.

**Comment by kasumi-1** [comment]
$100 MIST bounty (check #bounties in https://discord.gg/mistswapdex) - please write CLAIM here and submit PR within 1 day of claiming - if task is not completed within 3 day of claiming another user may claim to finish.

**Comment by mainnet-pat** [comment]
I can look into that.
Does it need to be fetched dynamically every now and then on the user side, or just ported over into this codebase?
